export const careers = [
  {
    position: "Staff IT",
    company: "Pt. Gisara Tantra Berkarya",
    logo: "/images/careers/gtb.webp",
    location: "Magelang, Indonesia",
    location_type: "Onsite",
    type: "Full-time",
    start_date: "2025-07",
    end_date: "2025-12",
    industry: "Manufacture",
    link: "https://www.gisaratantraberkarya.com/",
    responsibilities: [
      "Record and manage company IT assets (hardware inventory list, software licenses, and warranty periods).",
      "Managed and ensure all hardware (computers, laptops, printers, scanners, CCTV, routers) functions optimally.",
      "Providing technical support (troubleshooting) if problems occur with employee work equipment.",
    ],
    isShow: true,
  },
  {
    position: "Frontend Developer",
    company: "Pt. Lumintu Logic Indonesia",
    logo: "/images/careers/lumintu-logic.webp",
    location: "Yogyakarta, Indonesia",
    location_type: "Onsite",
    type: "Part-time",
    start_date: "2021-06",
    end_date: "2025-6",
    industry: "Software House",
    link: "https://lumintu-logic.com/",
    responsibilities: [
      "Developed a responsive and interactive Learning Management System (LMS) using Astro.js, focusing on performance, modular component architecture, and maintainable frontend structure.",
      "Implemented Astro Islands architecture with dynamic islands, combining SSR and SSG for optimal performance and interactivity.",
      "Collaborated with cross-functional stakeholders to translate brand requirements and business goals into a consistent and user-friendly web experience.",
    ],
    isShow: false,
  },
  {
    position: "Frontend Developer",
    company: "Pt. Transisi Teknologi Mandiri",
    logo: "/images/careers/ttm.webp",
    location: "Yogyakarta, Indonesia",
    location_type: "Hybrid",
    type: "Full-time",
    start_date: "2020-9",
    end_date: "2021-4",
    industry: "Software House",
    link: "https://transisi.id/",
    responsibilities: [
      "Developed and maintained Module ERP system using HTML,CSS Framework, PHP , focusing on reusable components and clean, maintainable code.",
      "Collaborated closely with Product Managers, QA developers, and Backend developers to translate business processes and requirements into well-tested, functional ERP features.",
      "Translated Wireframe FIGMA into functional and user-friendly web interfaces.",
    ],
    isShow: true,
  },
];